name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ${{secrets.REGISTRY_USER}}er/my-portfolio .
      - name: push image
      - run: 
             docker log -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASS}}
             docker push  ${{secrets.REGISTRY_USER}}/my-portfolio